Processing file: rcs-filter-smudge.py
 
 
pycodestyle:
 
checking rcs-filter-smudge.py
 
 
pylint:
 
No config file found, using default configuration
************* Module rcs-filter-smudge
C:  1, 0: Invalid module name "rcs-filter-smudge" (invalid-name)
R:252, 0: Too many local variables (27/15) (too-many-locals)
R:252, 0: Too many statements (70/50) (too-many-statements)

------------------------------------------------------------------
Your code has been rated at 9.84/10 (previous run: 9.84/10, -0.00)

  Entered module main
  Entered module startup_message
************ START **************
Hook program: rcs-filter-smudge.py
Hook path: 
Hook name: rcs-filter-smudge.py
*********************************
Start program name: rcs-filter-smudge.py
Python Call Graph v0.5.1
Starting trace
Caught exception, will raise after graph is made.
Creating rcs-filter-smudge.pdf
Done and raising the caught exception:
Traceback (most recent call last):
  File "/usr/bin/pycallgraph", line 147, in <module>
    execfile(args[0])
  File "rcs-filter-smudge.py", line 383, in <module>
    main(argv=sys.argv)
  File "rcs-filter-smudge.py", line 269, in main
    startup_message()
  File "rcs-filter-smudge.py", line 61, in startup_message
    sys.stderr.write('%s: %s\n' % (str(program_name), sys.argv[1]))
IndexError: list index out of range
